//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace varchar_128_.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class book_customer
    {
        public string id_book { get; set; }
        public string id_customer { get; set; }
        public System.DateTime date_of_issue { get; set; }
        public Nullable<System.DateTime> return_date { get; set; }
    
        public virtual book book { get; set; }
        public virtual customer customer { get; set; }
    }
}
